### ISSUE TITLE
Can't log in using Atom

### ISSUE THREAD

**Issue by jimovi24** [swdotcom/swdc-atom#2]
![image](https://user-images.githubusercontent.com/11744391/46876617-6e44e500-ce04-11e8-8166-0d90d6793fff.png)

Using Atom 1.31.2 64 bits
Packages:
Atom-beautify
Autoclose Html
Autocomplete
File Icons
Firacode
Pigments
Platformio-Ide-Terminal

**Comment by ElderTugBoat786** [comment]
Same error for me

**Comment by andrewhli** [comment]
Thanks for letting us know! Yes, one account on multiple PCs is a feature that we should support with 0 problems. We'll be sure to get this fixed for you. We believe this bug is related to a new feature last week that allows one user to have multiple Code Time accounts on one device (enabled a Log Out option). Right now, it looks like those features are creating problems (always showing 0 min coding for some users). We are fixing this today/tomorrow by going back to a simpler version without those extra features.

**Comment by brettmstevens7** [comment]
@ElderTugBoat786 @jimovi24 We've updated Atom to v0.5.1 which should address this issue. Let me know if you encounter any other problems and sorry about the bug.

**Comment by brettmstevens7** [comment]
I'm seeing this error now - will have a fix tomorrow morning.

**Comment by brettmstevens7** [comment]
Hi @ElderTugBoat786 @jimovi24 - it looks like we had an outdated version of our package in the Atom marketplace called `Software` that was returning a 401. The new version has been updated and you can find it here: https://atom.io/packages/code-time
